# Generated by Django 4.0.6 on 2022-11-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_newsitem_delete_newsitemmodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsitem",
            name="dead",
            field=models.BooleanField(
                default=False, help_text="true if the item is dead.", null=True
            ),
        ),
    ]
