# Generated by Django 4.0.6 on 2022-11-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_newsitem_text_alter_newsitem_title"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="newsitem",
            name="valid_comment_fields",
        ),
        migrations.RemoveConstraint(
            model_name="newsitem",
            name="valid_job_fields",
        ),
        migrations.RemoveConstraint(
            model_name="newsitem",
            name="valid_poll_fields",
        ),
        migrations.RemoveConstraint(
            model_name="newsitem",
            name="valid_polloption_fields",
        ),
        migrations.RemoveConstraint(
            model_name="newsitem",
            name="valid_story_fields",
        ),
        migrations.AddConstraint(
            model_name="newsitem",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("type", 5), _negated=True),
                    ("title__isnull", False),
                    _connector="OR",
                ),
                name="valid_story_fields",
            ),
        ),
    ]
