# Generated by Django 4.0.6 on 2022-11-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_newsitem_valid_comment_fields_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="newsitem",
            name="valid_job_fields",
        ),
        migrations.AddConstraint(
            model_name="newsitem",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("type", 2), _negated=True),
                    models.Q(("text__isnull", False), ("title__isnull", False)),
                    _connector="OR",
                ),
                name="valid_job_fields",
            ),
        ),
    ]
