# Generated by Django 4.0.6 on 2022-11-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_remove_newsitem_valid_job_fields_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsitem",
            name="hn_id",
            field=models.PositiveIntegerField(help_text="HackerNews ID", unique=True),
        ),
    ]
