# Generated by Django 4.1.3 on 2022-11-05 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0008_alter_newsitem_hn_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsitem",
            name="hn_id",
            field=models.PositiveIntegerField(help_text="HackerNews ID", null=True),
        ),
        migrations.AlterField(
            model_name="newsitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="The item's parent. For comments, either another comment or the relevant story. For pollopts, the relevant poll.                   Reverse relation: The ids of the item's comments, in ranked display order.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kids",
                to="news.newsitem",
            ),
        ),
        migrations.AlterField(
            model_name="newsitem",
            name="parent_poll",
            field=models.ForeignKey(
                blank=True,
                help_text="Reverse relation: A list of related pollopts, in display order.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parts",
                to="news.newsitem",
            ),
        ),
        migrations.AddConstraint(
            model_name="newsitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("hn_id__isnull", False)),
                fields=("hn_id",),
                name="unique_hn_id",
            ),
        ),
    ]
