# Generated by Django 4.1.3 on 2022-11-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0009_alter_newsitem_hn_id_alter_newsitem_parent_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="newsitem",
            name="valid_job_fields",
        ),
        migrations.AddConstraint(
            model_name="newsitem",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("type", 2), _negated=True),
                    ("text__isnull", False),
                    _connector="OR",
                ),
                name="valid_job_fields",
            ),
        ),
    ]
