# Generated by Django 4.0.6 on 2022-11-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0011_remove_newsitem_valid_job_fields_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="newsitem",
            name="valid_comment_fields",
        ),
        migrations.RemoveConstraint(
            model_name="newsitem",
            name="valid_poll_fields",
        ),
        migrations.RemoveConstraint(
            model_name="newsitem",
            name="valid_polloption_fields",
        ),
        migrations.AddConstraint(
            model_name="newsitem",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("type", 1), _negated=True),
                    ("text__isnull", False),
                    _connector="OR",
                ),
                name="valid_comment_fields",
            ),
        ),
        migrations.AddConstraint(
            model_name="newsitem",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("type", 3), _negated=True),
                    ("descendants__isnull", False),
                    _connector="OR",
                ),
                name="valid_poll_fields",
            ),
        ),
        migrations.AddConstraint(
            model_name="newsitem",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("type", 4), _negated=True),
                    ("parent__isnull", False),
                    _connector="OR",
                ),
                name="valid_polloption_fields",
            ),
        ),
    ]
